// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileHandler.proto

#include "fileHandler.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR fileInfoRequest::fileInfoRequest(
    ::_pbi::ConstantInitialized)
  : uid_(0){}
struct fileInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR fileInfoRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~fileInfoRequestDefaultTypeInternal() {}
  union {
    fileInfoRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 fileInfoRequestDefaultTypeInternal _fileInfoRequest_default_instance_;
PROTOBUF_CONSTEXPR fileInfo::fileInfo(
    ::_pbi::ConstantInitialized)
  : filename_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , createdat_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , updatedat_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , fileid_(0)
  , filesize_(0){}
struct fileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR fileInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~fileInfoDefaultTypeInternal() {}
  union {
    fileInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 fileInfoDefaultTypeInternal _fileInfo_default_instance_;
PROTOBUF_CONSTEXPR fileListResponse::fileListResponse(
    ::_pbi::ConstantInitialized)
  : files_()
  , msg_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , code_(0){}
struct fileListResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR fileListResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~fileListResponseDefaultTypeInternal() {}
  union {
    fileListResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 fileListResponseDefaultTypeInternal _fileListResponse_default_instance_;
static ::_pb::Metadata file_level_metadata_fileHandler_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_fileHandler_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_fileHandler_2eproto = nullptr;

const uint32_t TableStruct_fileHandler_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fileInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fileInfoRequest, uid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fileInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fileInfo, fileid_),
  PROTOBUF_FIELD_OFFSET(::fileInfo, filename_),
  PROTOBUF_FIELD_OFFSET(::fileInfo, filesize_),
  PROTOBUF_FIELD_OFFSET(::fileInfo, createdat_),
  PROTOBUF_FIELD_OFFSET(::fileInfo, updatedat_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fileListResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fileListResponse, code_),
  PROTOBUF_FIELD_OFFSET(::fileListResponse, msg_),
  PROTOBUF_FIELD_OFFSET(::fileListResponse, files_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::fileInfoRequest)},
  { 7, -1, -1, sizeof(::fileInfo)},
  { 18, -1, -1, sizeof(::fileListResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_fileInfoRequest_default_instance_._instance,
  &::_fileInfo_default_instance_._instance,
  &::_fileListResponse_default_instance_._instance,
};

const char descriptor_table_protodef_fileHandler_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021fileHandler.proto\"\036\n\017fileInfoRequest\022\013"
  "\n\003uid\030\001 \001(\005\"d\n\010fileInfo\022\016\n\006fileId\030\003 \001(\005\022"
  "\020\n\010filename\030\004 \001(\t\022\020\n\010filesize\030\005 \001(\005\022\021\n\tc"
  "reatedAt\030\006 \001(\t\022\021\n\tupdatedAt\030\007 \001(\t\"G\n\020fil"
  "eListResponse\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t"
  "\022\030\n\005files\030\003 \003(\0132\t.fileInfo2>\n\013fileHandle"
  "r\022/\n\010fileInfo\022\020.fileInfoRequest\032\021.fileLi"
  "stResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_fileHandler_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fileHandler_2eproto = {
    false, false, 298, descriptor_table_protodef_fileHandler_2eproto,
    "fileHandler.proto",
    &descriptor_table_fileHandler_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_fileHandler_2eproto::offsets,
    file_level_metadata_fileHandler_2eproto, file_level_enum_descriptors_fileHandler_2eproto,
    file_level_service_descriptors_fileHandler_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fileHandler_2eproto_getter() {
  return &descriptor_table_fileHandler_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fileHandler_2eproto(&descriptor_table_fileHandler_2eproto);

// ===================================================================

class fileInfoRequest::_Internal {
 public:
};

fileInfoRequest::fileInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:fileInfoRequest)
}
fileInfoRequest::fileInfoRequest(const fileInfoRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  uid_ = from.uid_;
  // @@protoc_insertion_point(copy_constructor:fileInfoRequest)
}

inline void fileInfoRequest::SharedCtor() {
uid_ = 0;
}

fileInfoRequest::~fileInfoRequest() {
  // @@protoc_insertion_point(destructor:fileInfoRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void fileInfoRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void fileInfoRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void fileInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fileInfoRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* fileInfoRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* fileInfoRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fileInfoRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fileInfoRequest)
  return target;
}

size_t fileInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fileInfoRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData fileInfoRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    fileInfoRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*fileInfoRequest::GetClassData() const { return &_class_data_; }

void fileInfoRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<fileInfoRequest *>(to)->MergeFrom(
      static_cast<const fileInfoRequest &>(from));
}


void fileInfoRequest::MergeFrom(const fileInfoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fileInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_uid() != 0) {
    _internal_set_uid(from._internal_uid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void fileInfoRequest::CopyFrom(const fileInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fileInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool fileInfoRequest::IsInitialized() const {
  return true;
}

void fileInfoRequest::InternalSwap(fileInfoRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(uid_, other->uid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata fileInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fileHandler_2eproto_getter, &descriptor_table_fileHandler_2eproto_once,
      file_level_metadata_fileHandler_2eproto[0]);
}

// ===================================================================

class fileInfo::_Internal {
 public:
};

fileInfo::fileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:fileInfo)
}
fileInfo::fileInfo(const fileInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    filename_.Set(from._internal_filename(), 
      GetArenaForAllocation());
  }
  createdat_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    createdat_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_createdat().empty()) {
    createdat_.Set(from._internal_createdat(), 
      GetArenaForAllocation());
  }
  updatedat_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    updatedat_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_updatedat().empty()) {
    updatedat_.Set(from._internal_updatedat(), 
      GetArenaForAllocation());
  }
  ::memcpy(&fileid_, &from.fileid_,
    static_cast<size_t>(reinterpret_cast<char*>(&filesize_) -
    reinterpret_cast<char*>(&fileid_)) + sizeof(filesize_));
  // @@protoc_insertion_point(copy_constructor:fileInfo)
}

inline void fileInfo::SharedCtor() {
filename_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  filename_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
createdat_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  createdat_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
updatedat_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  updatedat_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&fileid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&filesize_) -
    reinterpret_cast<char*>(&fileid_)) + sizeof(filesize_));
}

fileInfo::~fileInfo() {
  // @@protoc_insertion_point(destructor:fileInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void fileInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  filename_.Destroy();
  createdat_.Destroy();
  updatedat_.Destroy();
}

void fileInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void fileInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:fileInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filename_.ClearToEmpty();
  createdat_.ClearToEmpty();
  updatedat_.ClearToEmpty();
  ::memset(&fileid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&filesize_) -
      reinterpret_cast<char*>(&fileid_)) + sizeof(filesize_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* fileInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 fileId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          fileid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string filename = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fileInfo.filename"));
        } else
          goto handle_unusual;
        continue;
      // int32 filesize = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          filesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string createdAt = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_createdat();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fileInfo.createdAt"));
        } else
          goto handle_unusual;
        continue;
      // string updatedAt = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_updatedat();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fileInfo.updatedAt"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* fileInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fileInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 fileId = 3;
  if (this->_internal_fileid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_fileid(), target);
  }

  // string filename = 4;
  if (!this->_internal_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fileInfo.filename");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_filename(), target);
  }

  // int32 filesize = 5;
  if (this->_internal_filesize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_filesize(), target);
  }

  // string createdAt = 6;
  if (!this->_internal_createdat().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_createdat().data(), static_cast<int>(this->_internal_createdat().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fileInfo.createdAt");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_createdat(), target);
  }

  // string updatedAt = 7;
  if (!this->_internal_updatedat().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_updatedat().data(), static_cast<int>(this->_internal_updatedat().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fileInfo.updatedAt");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_updatedat(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fileInfo)
  return target;
}

size_t fileInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fileInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 4;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // string createdAt = 6;
  if (!this->_internal_createdat().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_createdat());
  }

  // string updatedAt = 7;
  if (!this->_internal_updatedat().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_updatedat());
  }

  // int32 fileId = 3;
  if (this->_internal_fileid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_fileid());
  }

  // int32 filesize = 5;
  if (this->_internal_filesize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_filesize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData fileInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    fileInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*fileInfo::GetClassData() const { return &_class_data_; }

void fileInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<fileInfo *>(to)->MergeFrom(
      static_cast<const fileInfo &>(from));
}


void fileInfo::MergeFrom(const fileInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fileInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _internal_set_filename(from._internal_filename());
  }
  if (!from._internal_createdat().empty()) {
    _internal_set_createdat(from._internal_createdat());
  }
  if (!from._internal_updatedat().empty()) {
    _internal_set_updatedat(from._internal_updatedat());
  }
  if (from._internal_fileid() != 0) {
    _internal_set_fileid(from._internal_fileid());
  }
  if (from._internal_filesize() != 0) {
    _internal_set_filesize(from._internal_filesize());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void fileInfo::CopyFrom(const fileInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fileInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool fileInfo::IsInitialized() const {
  return true;
}

void fileInfo::InternalSwap(fileInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &filename_, lhs_arena,
      &other->filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &createdat_, lhs_arena,
      &other->createdat_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &updatedat_, lhs_arena,
      &other->updatedat_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(fileInfo, filesize_)
      + sizeof(fileInfo::filesize_)
      - PROTOBUF_FIELD_OFFSET(fileInfo, fileid_)>(
          reinterpret_cast<char*>(&fileid_),
          reinterpret_cast<char*>(&other->fileid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata fileInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fileHandler_2eproto_getter, &descriptor_table_fileHandler_2eproto_once,
      file_level_metadata_fileHandler_2eproto[1]);
}

// ===================================================================

class fileListResponse::_Internal {
 public:
};

fileListResponse::fileListResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  files_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:fileListResponse)
}
fileListResponse::fileListResponse(const fileListResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      files_(from.files_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg().empty()) {
    msg_.Set(from._internal_msg(), 
      GetArenaForAllocation());
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:fileListResponse)
}

inline void fileListResponse::SharedCtor() {
msg_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  msg_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
code_ = 0;
}

fileListResponse::~fileListResponse() {
  // @@protoc_insertion_point(destructor:fileListResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void fileListResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  msg_.Destroy();
}

void fileListResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void fileListResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fileListResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  files_.Clear();
  msg_.ClearToEmpty();
  code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* fileListResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fileListResponse.msg"));
        } else
          goto handle_unusual;
        continue;
      // repeated .fileInfo files = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_files(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* fileListResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fileListResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg().data(), static_cast<int>(this->_internal_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fileListResponse.msg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_msg(), target);
  }

  // repeated .fileInfo files = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_files_size()); i < n; i++) {
    const auto& repfield = this->_internal_files(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fileListResponse)
  return target;
}

size_t fileListResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fileListResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .fileInfo files = 3;
  total_size += 1UL * this->_internal_files_size();
  for (const auto& msg : this->files_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData fileListResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    fileListResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*fileListResponse::GetClassData() const { return &_class_data_; }

void fileListResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<fileListResponse *>(to)->MergeFrom(
      static_cast<const fileListResponse &>(from));
}


void fileListResponse::MergeFrom(const fileListResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fileListResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  files_.MergeFrom(from.files_);
  if (!from._internal_msg().empty()) {
    _internal_set_msg(from._internal_msg());
  }
  if (from._internal_code() != 0) {
    _internal_set_code(from._internal_code());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void fileListResponse::CopyFrom(const fileListResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fileListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool fileListResponse::IsInitialized() const {
  return true;
}

void fileListResponse::InternalSwap(fileListResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  files_.InternalSwap(&other->files_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &msg_, lhs_arena,
      &other->msg_, rhs_arena
  );
  swap(code_, other->code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata fileListResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fileHandler_2eproto_getter, &descriptor_table_fileHandler_2eproto_once,
      file_level_metadata_fileHandler_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fileInfoRequest*
Arena::CreateMaybeMessage< ::fileInfoRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fileInfoRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::fileInfo*
Arena::CreateMaybeMessage< ::fileInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fileInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::fileListResponse*
Arena::CreateMaybeMessage< ::fileListResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fileListResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
