// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileHandler.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fileHandler_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_fileHandler_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fileHandler_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fileHandler_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fileHandler_2eproto;
class fileInfo;
struct fileInfoDefaultTypeInternal;
extern fileInfoDefaultTypeInternal _fileInfo_default_instance_;
class fileInfoRequest;
struct fileInfoRequestDefaultTypeInternal;
extern fileInfoRequestDefaultTypeInternal _fileInfoRequest_default_instance_;
class fileListResponse;
struct fileListResponseDefaultTypeInternal;
extern fileListResponseDefaultTypeInternal _fileListResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::fileInfo* Arena::CreateMaybeMessage<::fileInfo>(Arena*);
template<> ::fileInfoRequest* Arena::CreateMaybeMessage<::fileInfoRequest>(Arena*);
template<> ::fileListResponse* Arena::CreateMaybeMessage<::fileListResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class fileInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fileInfoRequest) */ {
 public:
  inline fileInfoRequest() : fileInfoRequest(nullptr) {}
  ~fileInfoRequest() override;
  explicit PROTOBUF_CONSTEXPR fileInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  fileInfoRequest(const fileInfoRequest& from);
  fileInfoRequest(fileInfoRequest&& from) noexcept
    : fileInfoRequest() {
    *this = ::std::move(from);
  }

  inline fileInfoRequest& operator=(const fileInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline fileInfoRequest& operator=(fileInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const fileInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const fileInfoRequest* internal_default_instance() {
    return reinterpret_cast<const fileInfoRequest*>(
               &_fileInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(fileInfoRequest& a, fileInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(fileInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(fileInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  fileInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<fileInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const fileInfoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const fileInfoRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(fileInfoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fileInfoRequest";
  }
  protected:
  explicit fileInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
  };
  // int32 uid = 1;
  void clear_uid();
  int32_t uid() const;
  void set_uid(int32_t value);
  private:
  int32_t _internal_uid() const;
  void _internal_set_uid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:fileInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t uid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_fileHandler_2eproto;
};
// -------------------------------------------------------------------

class fileInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fileInfo) */ {
 public:
  inline fileInfo() : fileInfo(nullptr) {}
  ~fileInfo() override;
  explicit PROTOBUF_CONSTEXPR fileInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  fileInfo(const fileInfo& from);
  fileInfo(fileInfo&& from) noexcept
    : fileInfo() {
    *this = ::std::move(from);
  }

  inline fileInfo& operator=(const fileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline fileInfo& operator=(fileInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const fileInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const fileInfo* internal_default_instance() {
    return reinterpret_cast<const fileInfo*>(
               &_fileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(fileInfo& a, fileInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(fileInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(fileInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  fileInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<fileInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const fileInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const fileInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(fileInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fileInfo";
  }
  protected:
  explicit fileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 4,
    kCreatedAtFieldNumber = 6,
    kUpdatedAtFieldNumber = 7,
    kFileIdFieldNumber = 3,
    kFilesizeFieldNumber = 5,
  };
  // string filename = 4;
  void clear_filename();
  const std::string& filename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string createdAt = 6;
  void clear_createdat();
  const std::string& createdat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_createdat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_createdat();
  PROTOBUF_NODISCARD std::string* release_createdat();
  void set_allocated_createdat(std::string* createdat);
  private:
  const std::string& _internal_createdat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_createdat(const std::string& value);
  std::string* _internal_mutable_createdat();
  public:

  // string updatedAt = 7;
  void clear_updatedat();
  const std::string& updatedat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_updatedat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_updatedat();
  PROTOBUF_NODISCARD std::string* release_updatedat();
  void set_allocated_updatedat(std::string* updatedat);
  private:
  const std::string& _internal_updatedat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_updatedat(const std::string& value);
  std::string* _internal_mutable_updatedat();
  public:

  // int32 fileId = 3;
  void clear_fileid();
  int32_t fileid() const;
  void set_fileid(int32_t value);
  private:
  int32_t _internal_fileid() const;
  void _internal_set_fileid(int32_t value);
  public:

  // int32 filesize = 5;
  void clear_filesize();
  int32_t filesize() const;
  void set_filesize(int32_t value);
  private:
  int32_t _internal_filesize() const;
  void _internal_set_filesize(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:fileInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr createdat_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr updatedat_;
  int32_t fileid_;
  int32_t filesize_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_fileHandler_2eproto;
};
// -------------------------------------------------------------------

class fileListResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fileListResponse) */ {
 public:
  inline fileListResponse() : fileListResponse(nullptr) {}
  ~fileListResponse() override;
  explicit PROTOBUF_CONSTEXPR fileListResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  fileListResponse(const fileListResponse& from);
  fileListResponse(fileListResponse&& from) noexcept
    : fileListResponse() {
    *this = ::std::move(from);
  }

  inline fileListResponse& operator=(const fileListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline fileListResponse& operator=(fileListResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const fileListResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const fileListResponse* internal_default_instance() {
    return reinterpret_cast<const fileListResponse*>(
               &_fileListResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(fileListResponse& a, fileListResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(fileListResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(fileListResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  fileListResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<fileListResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const fileListResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const fileListResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(fileListResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fileListResponse";
  }
  protected:
  explicit fileListResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesFieldNumber = 3,
    kMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // repeated .fileInfo files = 3;
  int files_size() const;
  private:
  int _internal_files_size() const;
  public:
  void clear_files();
  ::fileInfo* mutable_files(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fileInfo >*
      mutable_files();
  private:
  const ::fileInfo& _internal_files(int index) const;
  ::fileInfo* _internal_add_files();
  public:
  const ::fileInfo& files(int index) const;
  ::fileInfo* add_files();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fileInfo >&
      files() const;

  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:fileListResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fileInfo > files_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  int32_t code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_fileHandler_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// fileInfoRequest

// int32 uid = 1;
inline void fileInfoRequest::clear_uid() {
  uid_ = 0;
}
inline int32_t fileInfoRequest::_internal_uid() const {
  return uid_;
}
inline int32_t fileInfoRequest::uid() const {
  // @@protoc_insertion_point(field_get:fileInfoRequest.uid)
  return _internal_uid();
}
inline void fileInfoRequest::_internal_set_uid(int32_t value) {
  
  uid_ = value;
}
inline void fileInfoRequest::set_uid(int32_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:fileInfoRequest.uid)
}

// -------------------------------------------------------------------

// fileInfo

// int32 fileId = 3;
inline void fileInfo::clear_fileid() {
  fileid_ = 0;
}
inline int32_t fileInfo::_internal_fileid() const {
  return fileid_;
}
inline int32_t fileInfo::fileid() const {
  // @@protoc_insertion_point(field_get:fileInfo.fileId)
  return _internal_fileid();
}
inline void fileInfo::_internal_set_fileid(int32_t value) {
  
  fileid_ = value;
}
inline void fileInfo::set_fileid(int32_t value) {
  _internal_set_fileid(value);
  // @@protoc_insertion_point(field_set:fileInfo.fileId)
}

// string filename = 4;
inline void fileInfo::clear_filename() {
  filename_.ClearToEmpty();
}
inline const std::string& fileInfo::filename() const {
  // @@protoc_insertion_point(field_get:fileInfo.filename)
  return _internal_filename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void fileInfo::set_filename(ArgT0&& arg0, ArgT... args) {
 
 filename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fileInfo.filename)
}
inline std::string* fileInfo::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:fileInfo.filename)
  return _s;
}
inline const std::string& fileInfo::_internal_filename() const {
  return filename_.Get();
}
inline void fileInfo::_internal_set_filename(const std::string& value) {
  
  filename_.Set(value, GetArenaForAllocation());
}
inline std::string* fileInfo::_internal_mutable_filename() {
  
  return filename_.Mutable(GetArenaForAllocation());
}
inline std::string* fileInfo::release_filename() {
  // @@protoc_insertion_point(field_release:fileInfo.filename)
  return filename_.Release();
}
inline void fileInfo::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(filename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (filename_.IsDefault()) {
    filename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fileInfo.filename)
}

// int32 filesize = 5;
inline void fileInfo::clear_filesize() {
  filesize_ = 0;
}
inline int32_t fileInfo::_internal_filesize() const {
  return filesize_;
}
inline int32_t fileInfo::filesize() const {
  // @@protoc_insertion_point(field_get:fileInfo.filesize)
  return _internal_filesize();
}
inline void fileInfo::_internal_set_filesize(int32_t value) {
  
  filesize_ = value;
}
inline void fileInfo::set_filesize(int32_t value) {
  _internal_set_filesize(value);
  // @@protoc_insertion_point(field_set:fileInfo.filesize)
}

// string createdAt = 6;
inline void fileInfo::clear_createdat() {
  createdat_.ClearToEmpty();
}
inline const std::string& fileInfo::createdat() const {
  // @@protoc_insertion_point(field_get:fileInfo.createdAt)
  return _internal_createdat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void fileInfo::set_createdat(ArgT0&& arg0, ArgT... args) {
 
 createdat_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fileInfo.createdAt)
}
inline std::string* fileInfo::mutable_createdat() {
  std::string* _s = _internal_mutable_createdat();
  // @@protoc_insertion_point(field_mutable:fileInfo.createdAt)
  return _s;
}
inline const std::string& fileInfo::_internal_createdat() const {
  return createdat_.Get();
}
inline void fileInfo::_internal_set_createdat(const std::string& value) {
  
  createdat_.Set(value, GetArenaForAllocation());
}
inline std::string* fileInfo::_internal_mutable_createdat() {
  
  return createdat_.Mutable(GetArenaForAllocation());
}
inline std::string* fileInfo::release_createdat() {
  // @@protoc_insertion_point(field_release:fileInfo.createdAt)
  return createdat_.Release();
}
inline void fileInfo::set_allocated_createdat(std::string* createdat) {
  if (createdat != nullptr) {
    
  } else {
    
  }
  createdat_.SetAllocated(createdat, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (createdat_.IsDefault()) {
    createdat_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fileInfo.createdAt)
}

// string updatedAt = 7;
inline void fileInfo::clear_updatedat() {
  updatedat_.ClearToEmpty();
}
inline const std::string& fileInfo::updatedat() const {
  // @@protoc_insertion_point(field_get:fileInfo.updatedAt)
  return _internal_updatedat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void fileInfo::set_updatedat(ArgT0&& arg0, ArgT... args) {
 
 updatedat_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fileInfo.updatedAt)
}
inline std::string* fileInfo::mutable_updatedat() {
  std::string* _s = _internal_mutable_updatedat();
  // @@protoc_insertion_point(field_mutable:fileInfo.updatedAt)
  return _s;
}
inline const std::string& fileInfo::_internal_updatedat() const {
  return updatedat_.Get();
}
inline void fileInfo::_internal_set_updatedat(const std::string& value) {
  
  updatedat_.Set(value, GetArenaForAllocation());
}
inline std::string* fileInfo::_internal_mutable_updatedat() {
  
  return updatedat_.Mutable(GetArenaForAllocation());
}
inline std::string* fileInfo::release_updatedat() {
  // @@protoc_insertion_point(field_release:fileInfo.updatedAt)
  return updatedat_.Release();
}
inline void fileInfo::set_allocated_updatedat(std::string* updatedat) {
  if (updatedat != nullptr) {
    
  } else {
    
  }
  updatedat_.SetAllocated(updatedat, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (updatedat_.IsDefault()) {
    updatedat_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fileInfo.updatedAt)
}

// -------------------------------------------------------------------

// fileListResponse

// int32 code = 1;
inline void fileListResponse::clear_code() {
  code_ = 0;
}
inline int32_t fileListResponse::_internal_code() const {
  return code_;
}
inline int32_t fileListResponse::code() const {
  // @@protoc_insertion_point(field_get:fileListResponse.code)
  return _internal_code();
}
inline void fileListResponse::_internal_set_code(int32_t value) {
  
  code_ = value;
}
inline void fileListResponse::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:fileListResponse.code)
}

// string msg = 2;
inline void fileListResponse::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& fileListResponse::msg() const {
  // @@protoc_insertion_point(field_get:fileListResponse.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void fileListResponse::set_msg(ArgT0&& arg0, ArgT... args) {
 
 msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fileListResponse.msg)
}
inline std::string* fileListResponse::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:fileListResponse.msg)
  return _s;
}
inline const std::string& fileListResponse::_internal_msg() const {
  return msg_.Get();
}
inline void fileListResponse::_internal_set_msg(const std::string& value) {
  
  msg_.Set(value, GetArenaForAllocation());
}
inline std::string* fileListResponse::_internal_mutable_msg() {
  
  return msg_.Mutable(GetArenaForAllocation());
}
inline std::string* fileListResponse::release_msg() {
  // @@protoc_insertion_point(field_release:fileListResponse.msg)
  return msg_.Release();
}
inline void fileListResponse::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_.IsDefault()) {
    msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fileListResponse.msg)
}

// repeated .fileInfo files = 3;
inline int fileListResponse::_internal_files_size() const {
  return files_.size();
}
inline int fileListResponse::files_size() const {
  return _internal_files_size();
}
inline void fileListResponse::clear_files() {
  files_.Clear();
}
inline ::fileInfo* fileListResponse::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:fileListResponse.files)
  return files_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fileInfo >*
fileListResponse::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:fileListResponse.files)
  return &files_;
}
inline const ::fileInfo& fileListResponse::_internal_files(int index) const {
  return files_.Get(index);
}
inline const ::fileInfo& fileListResponse::files(int index) const {
  // @@protoc_insertion_point(field_get:fileListResponse.files)
  return _internal_files(index);
}
inline ::fileInfo* fileListResponse::_internal_add_files() {
  return files_.Add();
}
inline ::fileInfo* fileListResponse::add_files() {
  ::fileInfo* _add = _internal_add_files();
  // @@protoc_insertion_point(field_add:fileListResponse.files)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fileInfo >&
fileListResponse::files() const {
  // @@protoc_insertion_point(field_list:fileListResponse.files)
  return files_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_fileHandler_2eproto
