#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "fileHandler.pb.h"

namespace fileHandler
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void fileInfo(fileInfoRequest *request, fileListResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using fileInfoDone = std::function<void (fileListResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void fileInfo(const fileInfoRequest *req, fileInfoDone done);
	void fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> async_fileInfo(const fileInfoRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_fileInfo_task(fileInfoDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void fileInfo(const fileInfoRequest *req, fileInfoDone done);
	void fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> async_fileInfo(const fileInfoRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_fileInfo_task(fileInfoDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void fileInfo(const fileInfoRequest *req, fileInfoDone done);
	void fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> async_fileInfo(const fileInfoRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_fileInfo_task(fileInfoDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void fileInfo(const fileInfoRequest *req, fileInfoDone done);
	void fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> async_fileInfo(const fileInfoRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_fileInfo_task(fileInfoDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void fileInfo(const fileInfoRequest *req, fileInfoDone done);
	void fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> async_fileInfo(const fileInfoRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_fileInfo_task(fileInfoDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("fileHandler")
{
	this->srpc::RPCService::add_method("fileInfo",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::fileInfo);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("fileHandler")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("fileHandler")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::fileInfo(const fileInfoRequest *req, fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("fileInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_fileInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> SRPCClient::async_fileInfo(const fileInfoRequest *req)
{
	using RESULT = std::pair<fileListResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<fileListResponse>("fileInfo", srpc::RPCAsyncFutureCallback<fileListResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_fileInfo_task(fileInfoDone done)
{
	return this->create_rpc_client_task("fileInfo", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("fileHandler")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("fileHandler")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::fileInfo(const fileInfoRequest *req, fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("fileInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_fileInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_fileInfo(const fileInfoRequest *req)
{
	using RESULT = std::pair<fileListResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<fileListResponse>("fileInfo", srpc::RPCAsyncFutureCallback<fileListResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_fileInfo_task(fileInfoDone done)
{
	return this->create_rpc_client_task("fileInfo", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("fileHandler")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("fileHandler")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::fileInfo(const fileInfoRequest *req, fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("fileInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_fileInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> BRPCClient::async_fileInfo(const fileInfoRequest *req)
{
	using RESULT = std::pair<fileListResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<fileListResponse>("fileInfo", srpc::RPCAsyncFutureCallback<fileListResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_fileInfo_task(fileInfoDone done)
{
	return this->create_rpc_client_task("fileInfo", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("fileHandler")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("fileHandler")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::fileInfo(const fileInfoRequest *req, fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("/fileHandler/fileInfo", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_fileInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> TRPCClient::async_fileInfo(const fileInfoRequest *req)
{
	using RESULT = std::pair<fileListResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<fileListResponse>("/fileHandler/fileInfo", srpc::RPCAsyncFutureCallback<fileListResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_fileInfo_task(fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("/fileHandler/fileInfo", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("fileHandler")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("fileHandler")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::fileInfo(const fileInfoRequest *req, fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("fileInfo", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::fileInfo(const fileInfoRequest *req, fileListResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_fileInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<fileListResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_fileInfo(const fileInfoRequest *req)
{
	using RESULT = std::pair<fileListResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<fileListResponse>("fileInfo", srpc::RPCAsyncFutureCallback<fileListResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_fileInfo_task(fileInfoDone done)
{
	auto *task = this->create_rpc_client_task("fileInfo", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace fileHandler

